export const DATA = [
    {
        id: 1,
        img: "",
        title: "Gloomhaven (2017)",
        playersRating: "8.8",
        ourRating: "9.0",
        votersCount: 10,
        playingTime: "60-120min",
        complexity: "4.2",
        categories: ["Adventure", "Fantasy"],
        mechanics: ["Card Driven Campaign/Battle", "Role Playing"],
        ourReview: "",
        players: [1, 2, 3, 4, 5],
    },
    {
        id: 2,
        img: "",
        title: "Pandemic Legacy: Season 1 (2015)",
        playersRating: "8.7",
        ourRating: "8.5",
        votersCount: 10,
        playingTime: "60min",
        complexity: "4.2",
        categories: ["Adventure", "Legacy"],
        mechanics: ["Exploration"],
        ourReview: "",
        players: [2, 3, 4, 5],
    },
    {
        id: 3,
        img: "",
        title: "Terra Mystica (2017)",
        playersRating: "8.3",
        ourRating: "9.0",
        votersCount: 10,
        playingTime: "90-120min",
        complexity: "4.8",
        categories: ["Strategy", "Fantasy"],
        mechanics: ["Worker placement"],
        ourReview: "",
        players: [2, 3, 4, 5],
    },
    {
        id: 4,
        img: "",
        title: "Terraforming Mars (2016)",
        playersRating: "8.2",
        ourRating: "10.0",
        votersCount: 10,
        playingTime: "120min",
        complexity: "3.2",
        categories: ["Strategy"],
        mechanics: ["Worker placement", "Card drawing"],
        ourReview: "",
        players: [2, 3, 4],
    },
    {
        id: 5,
        img: "",
        title: "Star Wars: Rebellion (2016)",
        playersRating: "8.5",
        ourRating: "7.5",
        votersCount: 10,
        playingTime: "180-240min",
        complexity: "3.2",
        categories: ["Sci-Fi", "Strategy"],
        mechanics: ["Role playing", "Dice rolling"],
        ourReview: "",
        players: [2],
    },
    {
        id: 6,
        img: "",
        title: "Gaia Project (2017)",
        playersRating: "8.4",
        ourRating: "9.0",
        votersCount: 10,
        playingTime: "60-150min",
        complexity: "4.4",
        categories: ["Sci-Fi", "Strategy"],
        mechanics: ["Worker placement"],
        ourReview: "",
        players: [2, 3, 4, 5],
    },
    {
        id: 7,
        img: "",
        title: "Scythe (2016)",
        playersRating: "8.8",
        ourRating: "9.5",
        votersCount: 10,
        playingTime: "90-115min",
        complexity: "4.1",
        categories: ["Sci-Fi", "Strategy"],
        mechanics: ["Worker placement"],
        ourReview: "",
        players: [2, 3, 4, 5],
    },
    {
        id: 8,
        img: "",
        title: "7 Wonders Duel (2015)",
        playersRating: "8.9",
        ourRating: "7.0",
        votersCount: 10,
        playingTime: "30-45min",
        complexity: "2.8",
        categories: ["Strategy"],
        mechanics: ["Deck-building"],
        ourReview: "",
        players: [2],
    },
    {
        id: 9,
        img: "",
        title: "Wingspan (2019)",
        playersRating: "7.8",
        ourRating: "9.0",
        votersCount: 10,
        playingTime: "45min",
        complexity: "2.2",
        categories: ["Family", "Strategy"],
        mechanics: ["Deck-building"],
        ourReview: "",
        players: [1, 2, 3, 4, 5],
    },
    {
        id: 10,
        img: "",
        title: "Blood Rage (2015)",
        playersRating: "8.0",
        ourRating: "8.0",
        votersCount: 10,
        playingTime: "60-90min",
        complexity: "3.6",
        categories: ["Strategy"],
        mechanics: ["Battle", "Area Control"],
        ourReview: "",
        players: [2, 3, 4, 5],
    },
];

export const COMMENTS = [
    {
        author: "John Doe",
        text: "Great game, I can really recommend",
        rating: 9,
    },
    { author: "Jane Doe", text: "Not really in my type", rating: 5 },
    {
        author: "Walt Kowalski",
        text: "Slightly boring, but overall ok",
        rating: 7,
    },
    {
        author: "John Smith",
        text: "Best game ever",
        rating: 10,
    },
    {
        author: "Richard Patterson",
        text: "",
        rating: 3,
    },
];

export const CATEGORIES = [
    "Adventure",
    "Family",
    "Strategy",
    "Sci-Fi",
    "Fantasy",
    "Legacy",
    "Logic",
];
